import { Container } from "@/components/layout/container"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { toast } from "@/hooks/use-toast"
import { formatToIDR } from "@/utils/format-to-idr"
import { useUser } from "@clerk/nextjs"
import Head from "next/head"

interface GoldItemProps {
  label: string
  image: string
  quantity: number
  price: number
}

export default function TopupPage() {
  const topupItems = [
    {
      label: "10 gold",
      image: "/coins.png",
      quantity: 10,
      price: 10000,
    },
    {
      label: "50 gold",
      image: "/coins.png",
      quantity: 50,
      price: 50000,
    },
    {
      label: "100 gold",
      image: "/coins.png",
      quantity: 100,
      price: 100000,
    },
    {
      label: "300 gold",
      image: "/coins.png",
      quantity: 300,
      price: 300000,
    },
    {
      label: "600 gold",
      image: "/coins.png",
      quantity: 600,
      price: 600000,
    },
    {
      label: "1000 gold",
      image: "/coins.png",
      quantity: 1000,
      price: 1000000,
    },
  ]
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen w-full">
        <Container>
          <div className="mt-10 grid grid-cols-3 gap-6">
            {topupItems.map((item) => {
              return <GoldItem {...item} key={item.label} />
            })}
          </div>
        </Container>
      </main>
    </>
  )
}

const GoldItem = ({ image, label, quantity, price }: GoldItemProps) => {
  const { isSignedIn } = useUser()
  function handleTopup() {
    if (!isSignedIn) {
      toast({
        title: "anda belum login",
        description: "login terlebih dahulu untuk melakukan topup!",
        variant: "destructive",
      })
    } else {
      toast({
        title: "topup berhasil",
      })
    }
  }

  return (
    <Card
      onClick={handleTopup}
      className="flex flex-col items-center gap-4 px-4 py-8"
    >
      <img className="size-28" src={image} alt={label} />
      <span className="text-lg font-semibold capitalize dark:text-darkText">
        {quantity} gold
      </span>
      <Button variant="neutral">{formatToIDR(price)}</Button>
    </Card>
  )
}
