import { Container } from "@/components/layout/container"
import { env } from "@/env"
import Head from "next/head"
import { useEffect } from "react"
import { ListTopup } from "@/components/list-topup"

export default function TopupPage() {
  // run side effect to handle snap.pay
  useEffect(() => {
    const snapUrl = "https://app.sandbox.midtrans.com/snap/snap.js"
    const script = document.createElement("script")
    script.src = snapUrl
    script.setAttribute("data-client-key", env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY)

    document.body.appendChild(script)

    return () => {
      document.body.removeChild(script)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen w-full">
        <Container className="max-w-5xl">
          <ListTopup />
        </Container>
      </main>
    </>
  )
}
