import Head from "next/head"
import Link from "next/link"
import { SignUpButton } from "@clerk/nextjs"

import { api } from "@/utils/api"
import { Button } from "@/components/ui/button"
import { ThemeSwitcher } from "@/components/theme-swithcer"
import { Container } from "@/components/layout/container"
import { ListProducts } from "@/components/list-products"

export default function Home() {
  // const ctx = api.useUtils()
  // const hello = api.post.hello.useQuery({ text: "from tRPC" })
  // const { isPending, isError, mutate } = api.post.create.useMutation({
  //   onSuccess: async () => {
  //     // invalidate query after succes create post
  //     // invliadate getLatest query
  //     ctx.post.getLatest.invalidate()
  //   },
  // })

  //

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full">
        <Container>
          <ListProducts />
        </Container>
      </main>
    </>
  )
}
