import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"

import { TRPCReactProvider } from "@/trpc/react"
import { WithClerkProvider } from "@/components/clerk-provider"
import { Toaster } from "@/components/ui/toaster"
import { Navbar } from "@/components/layout/navbar"
import { Footer } from "@/components/footer"
import NextTopLoader from "nextjs-toploader"
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <WithClerkProvider>
      <TRPCReactProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${GeistSans.variable}`}>
            <ThemeProvider>
              <NextTopLoader color="#84ff00" height={3} showSpinner={false} />
              <Navbar />
              {children}
              <Footer />
              <Toaster />
            </ThemeProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </WithClerkProvider>
  )
}
