import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"

import { WithClerkProvider } from "@/components/provider/clerk-provider"
import { Toaster } from "@/components/ui/toaster"
import { Navbar } from "@/components/layout/navbar"
import { Footer } from "@/components/footer"
import NextTopLoader from "nextjs-toploader"
import { ThemeProvider } from "@/components/provider/theme-provider"
import { TanstackProvider } from "@/components/provider/tanstask-provider"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <WithClerkProvider>
      <TanstackProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${GeistSans.variable}`}>
            <ThemeProvider>
              <NextTopLoader color="#fc7303" height={3} showSpinner={false} />
              <Navbar />
              {children}
              <Footer />
              <Toaster />
            </ThemeProvider>
          </body>
        </html>
      </TanstackProvider>
    </WithClerkProvider>
  )
}
